version: '3.8'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"
      - "5173:5173"
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - devnet
volumes:
  dbdata:
networks:
  devnet:
